name: Build Raspberry Pi Jamulus Image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo apt-get clean
          df -h

      - uses: usimd/pi-gen-action@v1
        with:
          image-name: rpi4-jamulus
          pi-gen-repository: RPi-Distro/pi-gen
          pi-gen-version: arm64
          release: bookworm
          stage-list: stage0 stage1 stage2 stage-jamulus
          compression: xz
          enable-ssh: 1
          username: pi
          password: jamulus
          disable-first-boot-user-rename: 1
          hostname: jamulus-pi
          keyboard-layout: us
          timezone: America/Sao_Paulo
          extra-host-dependencies: sudo
          export-last-stage-only: true
          increase-runner-disk-size: true
          verbose-output: true
          apt-purge-packages: ''

      - uses: actions/upload-artifact@v4
        with:
          name: rpi4-jamulus-image
          path: pi-gen/deploy/*